[package]
name = "bob_miner_v2"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "bob_miner_v2"
path = "src/main.rs"

[dependencies]
candid = "0.10.11"
candid_parser = "0.2.0-beta.4"
ic-cdk = "0.17.1"
ic-cdk-timers = "0.11.0"
serde = "1.0.209"
