name: 'Tests'

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  # When getting Rust dependencies, retry on network error:
  CARGO_NET_RETRY: 10
  # Use the local .curlrc
  CURL_HOME: .
  # sscache environment variables
  SCCACHE_GHA_ENABLED: 'true'
  RUSTC_WRAPPER: 'sccache'

jobs:
  unit-tests:
    name: 'unit-tests:required'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Set up Rust'
        uses: mozilla-actions/sccache-action@v0.0.4
      - name: 'Download ic-wasm'
        run: |
          curl -L https://github.com/dfinity/ic-wasm/releases/download/0.9.1/ic-wasm-linux64 -o /usr/local/bin/ic-wasm
          chmod +x /usr/local/bin/ic-wasm
      - name: 'Build BoB'
        run: |
          ./build.sh
      - name: 'Test cargo crates'
        run: |
          cargo test --locked --workspace --exclude integration-tests
  integration-tests:
    name: 'integration-tests:required'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Set up Rust'
        uses: mozilla-actions/sccache-action@v0.0.4
      - name: 'Download ic-wasm'
        run: |
          curl -L https://github.com/dfinity/ic-wasm/releases/download/0.9.1/ic-wasm-linux64 -o /usr/local/bin/ic-wasm
          chmod +x /usr/local/bin/ic-wasm
      - name: 'Integration tests'
        run: |
          ./scripts/run-integration-tests.sh
