name: 'Code validation'

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  # When getting Rust dependencies, retry on network error:
  CARGO_NET_RETRY: 10
  # Use the local .curlrc
  CURL_HOME: .

jobs:
  validate-rust:
    name: 'validate-rust:required'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Set up Rust'
        uses: mozilla-actions/sccache-action@v0.0.4
      - name: 'Download ic-wasm'
        run: |
          curl -L https://github.com/dfinity/ic-wasm/releases/download/0.9.1/ic-wasm-linux64 -o /usr/local/bin/ic-wasm
          chmod +x /usr/local/bin/ic-wasm
      - name: 'Build BoB'
        run: |
          ./build.sh
      - name: 'Check code'
        run: |
          cargo fmt --all -- --check
          cargo clippy --locked --verbose --tests --workspace -- -D clippy::all
          cargo clippy --locked --verbose --target wasm32-unknown-unknown -p bob_miner_v2 -p bob-minter-v2 -- -D clippy::all
        env:
          RUST_BACKTRACE: 1
